apiVersion: v1
kind: Config
clusters:
  - name: default
    cluster:
      server: https://192.168.1.6:6443
      certificate-authority-data: KUBE_CLUSTER_CERT
      insecure-skip-tls-verify: false
users:
  - name: default
    user:
      client-certificate-data: KUBE_CLIENT_CERT
      client-key-data: KUBE_CLIENT_KEY
contexts:
  - name: default
    context:
      cluster: default
      name: default
      user: default
      namespace: default
preferences: {}
current-context: default
