kind: pipeline
type: kubernetes
name: default

steps:
  - name: build-image
      image: docker:dind
      volumes:
        - name: dockersock
          path: /var/run/
      commands:
        - docker build -t cr.seen.wtf/aa-webapp .
        - docker push cr.seen.wtf/aa-webapp

volumes:
  - name: dockersock
    temp: {}