kind: pipeline
type: kubernetes
name: default

steps:
  - name: semantic-release
    image: cr.seen.wtf/semantic-release
    environment:
      GH_TOKEN:
        from_secret: GITHUB_TOKEN
    volumes:
      - name: dockersock
        path: /var/run/
    commands:
      - apt update && apt upgrade && apt install docker.io -y
      - npm i -g @semantic-release-plus/docker
      - docker build -t webapp .
      - semantic-release
    
  - name: build-image
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/
    commands:
      - sleep 10
      - docker build -t cr.seen.wtf/aa-webapp .
      - docker push cr.seen.wtf/aa-webapp

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run


volumes:
  - name: dockersock
    temp: {}